version: "3.7"
services:
    app:
        image: "ptrvsrg/professor-base-forms:latest"
        container_name: "professor-base-app"
        env_file:
            - ./.env
        ports:
            - "8000:8000"
        networks:
            - professor-base-net
        depends_on:
            - db
    db:
        image: "postgres:latest"
        container_name: "professor-base-db"
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - "5432:5432"
        volumes:
            - "professor-base-db-data:/var/lib/postgresql/data"
            - "./sql:/docker-entrypoint-initdb.d/"
        networks:
            - professor-base-net
volumes:
    professor-base-db-data:
        name: professor-base-db-data
networks:
    professor-base-net:
        name: professor-base-net
